// Skill Guide — mock data drawn from the screenshot
// Tags taxonomy: ระเบิด, CC, AoE, ลดดาเมจ, บัฟ, ฮีล, ปลดCC, Mobility, Counter,
//                ทุบไล่ (Launch/Pursuit), เดี่ยว, ต่อเนื่อง, สะสมพลัง, ระยะไกล,
//                ไล่, ตัวเอง, เคลื่อนที่, ลด CD, ปล่อยตัว, สะท้อน, กลุ่ม, สุ่มผล,
//                passive, ช่วย, ย้าย

window.SKILLS = [
  { n: 1,  name: 'หมึกทลายแผ่นดิน',     tags: ['ระเบิด','CC','เดี่ยว'],            hint: 'แม่นยำ 930 → hit rate ดี',          cd: 15, rec: 1,  role: 'DPS' },
  { n: 2,  name: 'จันทร์เหมันต์ดุจเดียว',  tags: ['ระเบิด','สะสมพลัง','AoE'],         hint: 'คริ 1368 → โอกาสคริสูง',         cd: 18, rec: 1,  role: 'DPS' },
  { n: 3,  name: 'ทวนสายฟ้าฟาด',        tags: ['ระเบิด','ระยะไกล','AoE'],          hint: 'คริ 1368 → โอกาสคริสูง',         cd: 18, rec: 1,  role: 'DPS' },
  { n: 4,  name: 'โฝสวรรค์พิชิตอัสนี',     tags: ['ระเบิด','CC','AoE'],              hint: 'คริ 1368 → โอกาสคริสูง',         cd: 24, rec: 1,  role: 'DPS' },
  { n: 5,  name: 'ดัชนีเสียงวิหค',         tags: ['เดี่ยว','ทุบไล่','ลด CD'],          hint: '',                                cd: 15, rec: 'good', role: 'DPS' },
  { n: 6,  name: 'พายุหมุนโลกกันตร์',     tags: ['ต่อเนื่อง','ทุบไล่','ลด CD'],        hint: '',                                cd: 13, rec: 'good', role: 'DPS' },
  { n: 7,  name: 'คาถาเปลี่ยนชีวิต',       tags: ['ระเบิด','บัฟ','ตัวเอง'],            hint: 'คริ 1368 → โอกาสคริสูง',         cd: 24, rec: 1,  role: 'Support' },
  { n: 8,  name: 'ทลายโกลาหล',           tags: ['ระเบิด','ลดดาเมจ','Mobility'],     hint: '',                                cd: 22, rec: 'good', role: 'DPS' },
  { n: 9,  name: 'วิชากระบี่นึงรัก',         tags: ['ระเบิด','เคลื่อนที่','ทุบไล่'],         hint: '',                                cd: 20, rec: 'good', role: 'DPS' },
  { n: 10, name: 'ฝ่ามือแดนมนุษย์',        tags: ['เดี่ยว','ต่อเนื่อง','ทุบไล่'],          hint: 'แม่นยำ 930 → hit rate ดี',          cd: 20, rec: 1,  role: 'DPS' },
  { n: 11, name: 'อัสนีบาต',              tags: ['เดี่ยว','ระเบิด','CC'],             hint: 'แม่นยำ 930 → hit rate ดี',          cd: 18, rec: 1,  role: 'DPS' },
  { n: 12, name: 'ร่มแดงพิฆาต',           tags: ['ระเบิด','AoE','เคลื่อนที่'],          hint: 'คริ 1368 → โอกาสคริสูง',         cd: 15, rec: 1,  role: 'DPS' },
  { n: 13, name: 'มังกรเหินน้ำคำราม',      tags: ['ระเบิด','CC','ปล่อยตัว'],           hint: '',                                cd: 18, rec: null, role: 'DPS' },
  { n: 14, name: 'ระฆังทองคงกระพัน',      tags: ['เดี่ยว','ลดดาเมจ','สะท้อน'],         hint: '',                                cd: 55, rec: null, role: 'Tank' },
  { n: 15, name: 'แขนอรหันต์',            tags: ['เดี่ยว','เคลื่อนที่','ลด CD'],          hint: '',                                cd: 19, rec: null, role: 'Support' },
  { n: 16, name: 'ทำนายฟ้าดิน',           tags: ['กลุ่ม','สุ่มผล','บัฟ'],               hint: '',                                cd: 12, rec: null, role: 'Support' },
  { n: 17, name: 'วิชาวานร',              tags: ['เดี่ยว','บัฟ','passive'],            hint: '',                                cd: 3,  rec: null, role: 'Support' },
  { n: 18, name: 'ท่าปราบพยัคฆ์',          tags: ['เดี่ยว','บัฟ','ช่วย'],               hint: '',                                cd: 30, rec: null, role: 'Support' },
  { n: 19, name: 'ฝ่ามือพยัคฆ์ขาว',         tags: ['เดี่ยว','ทุบไล่'],                   hint: '',                                cd: 12, rec: null, role: 'DPS' },
  { n: 20, name: 'พิรุณคลั่ง',              tags: ['AoE','ต่อเนื่อง','ลดดาเมจ'],        hint: '',                                cd: 24, rec: null, role: 'Tank' },
  { n: 21, name: 'มีดเมฆใต้พิภพ',          tags: ['เดี่ยว','ระยะไกล','CC'],            hint: 'แม่นยำ 930 → hit rate ดี',          cd: 17, rec: 1,  role: 'DPS' },
  { n: 22, name: 'หยกเย็นยะเยือก',         tags: ['CC','AoE','ลดดาเมจ'],            hint: '',                                cd: 28, rec: null, role: 'Tank' },
  { n: 23, name: 'ลมเหนือนิรันดร์',         tags: ['Mobility','บัฟ','ตัวเอง'],          hint: '',                                cd: 22, rec: null, role: 'Support' },
  { n: 24, name: 'อสรพิษทมิฬ',            tags: ['ระเบิด','พิษ','ต่อเนื่อง'],           hint: 'คริ 1368 → โอกาสคริสูง',         cd: 16, rec: 'good', role: 'DPS' },
  { n: 25, name: 'แสงพระพุทธ',           tags: ['ฮีล','AoE','บัฟ'],                  hint: '',                                cd: 32, rec: null, role: 'Heal' },
  { n: 26, name: 'มีดบินหมื่นทาง',          tags: ['ระเบิด','ระยะไกล','AoE'],          hint: 'คริ 1368 → โอกาสคริสูง',         cd: 19, rec: 'good', role: 'DPS' },
  { n: 27, name: 'น้ำคำราม',              tags: ['CC','ปล่อยตัว','AoE'],             hint: '',                                cd: 24, rec: null, role: 'DPS' },
  { n: 28, name: 'ฉางลั่งเทียนเทียบ',        tags: ['Counter','สะท้อน','ลดดาเมจ'],     hint: '',                                cd: 35, rec: null, role: 'Tank' },
  { n: 29, name: 'นาคีพันเขา',            tags: ['CC','ต่อเนื่อง','เดี่ยว'],            hint: 'แม่นยำ 930 → hit rate ดี',          cd: 14, rec: 'good', role: 'DPS' },
  { n: 30, name: 'ลายมือผีเสื้อ',           tags: ['Mobility','เคลื่อนที่','ปลดCC'],     hint: '',                                cd: 18, rec: null, role: 'Support' },
  { n: 31, name: 'กระบี่ปลอบขวัญ',         tags: ['ฮีล','ตัวเอง','ลด CD'],             hint: '',                                cd: 25, rec: null, role: 'Heal' },
  { n: 32, name: 'อมตะเก้าชั้นฟ้า',         tags: ['บัฟ','ตัวเอง','passive'],           hint: '',                                cd: 0,  rec: null, role: 'Support' },
  { n: 33, name: 'มรณะวารวสันต์',         tags: ['ระเบิด','สะสมพลัง','เดี่ยว'],         hint: 'คริ 1368 → โอกาสคริสูง',         cd: 30, rec: 1,  role: 'DPS' },
  { n: 34, name: 'จันทร์ลับฟ้า',            tags: ['CC','Launch','ทุบไล่'],            hint: '',                                cd: 16, rec: 'good', role: 'DPS' },
  { n: 35, name: 'ฉางลั่งเทียนเทียบ',        tags: ['ฮีล','กลุ่ม','ปลดCC'],              hint: '',                                cd: 28, rec: null, role: 'Heal' },
  { n: 36, name: 'มังกรพันธ์เก้าทิศ',         tags: ['AoE','CC','ต่อเนื่อง'],            hint: '',                                cd: 24, rec: null, role: 'DPS' },
  { n: 37, name: 'พายุหิมะ',              tags: ['AoE','ลดดาเมจ','ต่อเนื่อง'],        hint: '',                                cd: 20, rec: null, role: 'Tank' },
  { n: 38, name: 'ดาวสมุทรนิรันดร์',        tags: ['Mobility','ปลดCC','บัฟ'],           hint: '',                                cd: 26, rec: null, role: 'Support' },
  { n: 39, name: 'รัศมีฟ้าทอ',             tags: ['ฮีล','บัฟ','AoE'],                 hint: '',                                cd: 22, rec: null, role: 'Heal' },
  { n: 40, name: 'ทับซับจิต',              tags: ['Counter','ลดดาเมจ','สะท้อน'],     hint: '',                                cd: 32, rec: null, role: 'Tank' },
  { n: 41, name: 'ปฐมพยัคฆ์',            tags: ['ระเบิด','CC','เดี่ยว'],             hint: 'แม่นยำ 930 → hit rate ดี',          cd: 13, rec: 1,  role: 'DPS' },
  { n: 42, name: 'หมุนสุริยกัน',            tags: ['AoE','สะสมพลัง','ทุบไล่'],         hint: 'คริ 1368 → โอกาสคริสูง',         cd: 21, rec: 'good', role: 'DPS' },
  { n: 43, name: 'รังนกอินทรี',            tags: ['Mobility','ตัวเอง','passive'],       hint: '',                                cd: 0,  rec: null, role: 'Support' },
  { n: 44, name: 'ดาบกลืนวิญญาณ',        tags: ['ระเบิด','พิษ','ต่อเนื่อง'],           hint: 'คริ 1368 → โอกาสคริสูง',         cd: 20, rec: 'good', role: 'DPS' },
  { n: 45, name: 'พัดเงาเสน่ห์',           tags: ['CC','ระยะไกล','สุ่มผล'],            hint: '',                                cd: 17, rec: null, role: 'Support' },
  { n: 46, name: 'พลังต้องคงคำ',           tags: ['ลดดาเมจ','บัฟ','กลุ่ม'],            hint: '',                                cd: 28, rec: null, role: 'Tank' },
  { n: 47, name: 'แสงเลือดมังกร',          tags: ['ระเบิด','AoE','พิษ'],              hint: 'คริ 1368 → โอกาสคริสูง',         cd: 25, rec: 'good', role: 'DPS' },
  { n: 48, name: 'จันทราเงาคู่',            tags: ['Mobility','Counter','สะท้อน'],     hint: '',                                cd: 19, rec: null, role: 'Tank' },
];

// Tag → category — drives a small color dot on the tag chip.
// Categories: attack, cc, area, defense, support, mobility, utility
window.TAG_CATEGORY = {
  'ระเบิด':     'attack',
  'พิษ':         'attack',
  'ทุบไล่':       'attack',
  'Launch':     'attack',
  'สะสมพลัง':    'attack',
  'CC':         'cc',
  'ปลดCC':      'cc',
  'Counter':    'cc',
  'สะท้อน':      'cc',
  'AoE':        'area',
  'กลุ่ม':        'area',
  'ระยะไกล':     'area',
  'ลดดาเมจ':    'defense',
  'บัฟ':         'support',
  'ฮีล':         'support',
  'ช่วย':         'support',
  'Mobility':   'mobility',
  'เคลื่อนที่':     'mobility',
  'ปล่อยตัว':     'mobility',
  'เดี่ยว':       'utility',
  'ต่อเนื่อง':     'utility',
  'ตัวเอง':       'utility',
  'ลด CD':      'utility',
  'สุ่มผล':       'utility',
  'passive':    'utility',
};

window.HIGHLIGHT_TAGS = ['ทุบไล่','CC','ระเบิด','AoE','ลดดาเมจ','บัฟ','ฮีล','ปลดCC','Mobility','Counter','Launch'];
window.ROLES = ['ทั้งหมด','DPS','Tank','Heal','Support'];
